import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Customer } from './customer';

@Injectable()
export class CustomerService {
  constructor(private http: HttpClient) {}

  getCustomersLarge() {
    return this.http
      .get<any>('assets/customers-large.json')
      .toPromise()
      .then((res) => res.data as Customer[])
      .then((data) => data);
  }

  // Fallback method if the HTTP request fails (for demo purposes)
  getMockCustomers(): Promise<Customer[]> {
    return Promise.resolve([
        {
            id: '1000',
            name: 'James Butt',
            country: { name: 'Algeria', code: 'dz' },
            company: 'Benton, John B Jr',
            date: new Date(2015, 9, 13),
            status: 'unqualified',
            activity: 17,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 70663,
          },
          {
            id: '1001',
            name: 'Josephine Darakjy',
            country: { name: 'Egypt', code: 'eg' },
            company: 'Chanay, Jeffrey A Esq',
            date: new Date(2019, 2, 9),
            status: 'proposal',
            activity: 0,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 82429,
          },
          {
            id: '1002',
            name: 'Art Venere',
            country: { name: 'Panama', code: 'pa' },
            company: 'Chemel, James L Cpa',
            date: new Date(2017, 11, 18),
            status: 'qualified',
            activity: 63,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 28334,
          },
          {
            id: '1003',
            name: 'Lenna Paprocki',
            country: { name: 'Slovenia', code: 'si' },
            company: 'Feltz Printing Service',
            date: new Date(2020, 9, 15),
            status: 'new',
            activity: 37,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 88521,
          },
          {
            id: '1004',
            name: 'Donette Foller',
            country: { name: 'South Africa', code: 'za' },
            company: 'Printing Dimensions',
            date: new Date(2016, 5, 20),
            status: 'proposal',
            activity: 33,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 93905,
          },
          {
            id: '1005',
            name: 'Michael Carter',
            country: { name: 'Brazil', code: 'br' },
            company: 'Carter Enterprises',
            date: new Date(2018, 3, 22),
            status: 'new',
            activity: 45,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 45678,
          },
          {
            id: '1006',
            name: 'Sophie Laurent',
            country: { name: 'France', code: 'fr' },
            company: 'Laurent Designs',
            date: new Date(2019, 7, 10),
            status: 'qualified',
            activity: 82,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 67890,
          },
          {
            id: '1007',
            name: 'Hiroshi Tanaka',
            country: { name: 'Japan', code: 'jp' },
            company: 'Tanaka Solutions',
            date: new Date(2020, 1, 15),
            status: 'proposal',
            activity: 19,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 34567,
          },
          {
            id: '1008',
            name: 'Elena Morales',
            country: { name: 'Spain', code: 'es' },
            company: 'Morales Consulting',
            date: new Date(2017, 6, 30),
            status: 'unqualified',
            activity: 27,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 78901,
          },
          {
            id: '1009',
            name: 'Liam O’Connor',
            country: { name: 'Ireland', code: 'ie' },
            company: 'O’Connor Tech',
            date: new Date(2016, 11, 5),
            status: 'new',
            activity: 56,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 23456,
          },
          {
            id: '1010',
            name: 'Aisha Khan',
            country: { name: 'Pakistan', code: 'pk' },
            company: 'Khan Innovations',
            date: new Date(2021, 4, 12),
            status: 'qualified',
            activity: 73,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 56789,
          },
          {
            id: '1011',
            name: 'Lucas Schmidt',
            country: { name: 'Germany', code: 'de' },
            company: 'Schmidt GmbH',
            date: new Date(2015, 12, 8),
            status: 'proposal',
            activity: 41,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 89012,
          },
          {
            id: '1012',
            name: 'Isabella Rossi',
            country: { name: 'Italy', code: 'it' },
            company: 'Rossi Creations',
            date: new Date(2019, 9, 25),
            status: 'unqualified',
            activity: 32,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 12345,
          },
          {
            id: '1013',
            name: 'Chen Wei',
            country: { name: 'China', code: 'cn' },
            company: 'Wei Technologies',
            date: new Date(2020, 6, 18),
            status: 'new',
            activity: 68,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 45612,
          },
          {
            id: '1014',
            name: 'Olivia Brown',
            country: { name: 'Australia', code: 'au' },
            company: 'Brown Ventures',
            date: new Date(2018, 2, 14),
            status: 'qualified',
            activity: 29,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 67834,
          },
          {
            id: '1015',
            name: 'Mateo Lopez',
            country: { name: 'Mexico', code: 'mx' },
            company: 'Lopez Industries',
            date: new Date(2017, 8, 3),
            status: 'proposal',
            activity: 51,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 34512,
          },
          {
            id: '1016',
            name: 'Fatima Al-Sayed',
            country: { name: 'Saudi Arabia', code: 'sa' },
            company: 'Al-Sayed Group',
            date: new Date(2016, 4, 27),
            status: 'unqualified',
            activity: 44,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 78934,
          },
          {
            id: '1017',
            name: 'Noah Kim',
            country: { name: 'South Korea', code: 'kr' },
            company: 'Kim Dynamics',
            date: new Date(2021, 2, 19),
            status: 'new',
            activity: 62,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 23478,
          },
          {
            id: '1018',
            name: 'Emma Wilson',
            country: { name: 'United Kingdom', code: 'gb' },
            company: 'Wilson Analytics',
            date: new Date(2019, 5, 7),
            status: 'qualified',
            activity: 38,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 56712,
          },
          {
            id: '1019',
            name: 'Arjun Patel',
            country: { name: 'India', code: 'in' },
            company: 'Patel Solutions',
            date: new Date(2018, 10, 22),
            status: 'proposal',
            activity: 75,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 89056,
          },
          {
            id: '1020',
            name: 'Sofia Andersen',
            country: { name: 'Denmark', code: 'dk' },
            company: 'Andersen Consulting',
            date: new Date(2017, 3, 11),
            status: 'unqualified',
            activity: 23,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 12378,
          },
          {
            id: '1021',
            name: 'Gabriel Silva',
            country: { name: 'Portugal', code: 'pt' },
            company: 'Silva Enterprises',
            date: new Date(2020, 8, 9),
            status: 'new',
            activity: 67,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 45634,
          },
          {
            id: '1022',
            name: 'Anastasia Petrova',
            country: { name: 'Russia', code: 'ru' },
            company: 'Petrova Tech',
            date: new Date(2016, 12, 15),
            status: 'qualified',
            activity: 31,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 67856,
          },
          {
            id: '1023',
            name: 'Lars Eriksson',
            country: { name: 'Sweden', code: 'se' },
            company: 'Eriksson Innovations',
            date: new Date(2019, 1, 28),
            status: 'proposal',
            activity: 49,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 34578,
          },
          {
            id: '1024',
            name: 'Mia Nguyen',
            country: { name: 'Vietnam', code: 'vn' },
            company: 'Nguyen Solutions',
            date: new Date(2018, 7, 16),
            status: 'unqualified',
            activity: 52,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 78956,
          },
          {
            id: '1025',
            name: 'Ethan Clark',
            country: { name: 'Canada', code: 'ca' },
            company: 'Clark Ventures',
            date: new Date(2021, 3, 5),
            status: 'new',
            activity: 64,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 23412,
          },
          {
            id: '1026',
            name: 'Zoe Martinez',
            country: { name: 'Argentina', code: 'ar' },
            company: 'Martinez Group',
            date: new Date(2017, 9, 20),
            status: 'qualified',
            activity: 36,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 56734,
          },
          {
            id: '1027',
            name: 'Omar Farooq',
            country: { name: 'United Arab Emirates', code: 'ae' },
            company: 'Farooq Enterprises',
            date: new Date(2016, 5, 13),
            status: 'proposal',
            activity: 71,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 89034,
          },
          {
            id: '1028',
            name: 'Chloe Lee',
            country: { name: 'Singapore', code: 'sg' },
            company: 'Lee Technologies',
            date: new Date(2020, 11, 2),
            status: 'unqualified',
            activity: 28,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 12312,
          },
          {
            id: '1029',
            name: 'Julian Weber',
            country: { name: 'Switzerland', code: 'ch' },
            company: 'Weber Solutions',
            date: new Date(2019, 4, 17),
            status: 'new',
            activity: 59,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 45678,
          },
          {
            id: '1030',
            name: 'Amara Diallo',
            country: { name: 'Senegal', code: 'sn' },
            company: 'Diallo Ventures',
            date: new Date(2018, 6, 24),
            status: 'qualified',
            activity: 47,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 67890,
          },
          {
            id: '1031',
            name: 'Sebastian Garcia',
            country: { name: 'Chile', code: 'cl' },
            company: 'Garcia Innovations',
            date: new Date(2017, 2, 9),
            status: 'proposal',
            activity: 65,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 34512,
          },
          {
            id: '1032',
            name: 'Layla Hassan',
            country: { name: 'Morocco', code: 'ma' },
            company: 'Hassan Group',
            date: new Date(2021, 1, 13),
            status: 'unqualified',
            activity: 34,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 78934,
          },
          {
            id: '1033',
            name: 'Elias Jensen',
            country: { name: 'Norway', code: 'no' },
            company: 'Jensen Tech',
            date: new Date(2016, 10, 29),
            status: 'new',
            activity: 53,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 23456,
          },
          {
            id: '1034',
            name: 'Ava Patel',
            country: { name: 'New Zealand', code: 'nz' },
            company: 'Patel Enterprises',
            date: new Date(2019, 8, 4),
            status: 'qualified',
            activity: 76,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 56789,
          },
          {
            id: '1035',
            name: 'Youssef Ali',
            country: { name: 'Lebanon', code: 'lb' },
            company: 'Ali Solutions',
            date: new Date(2018, 12, 16),
            status: 'proposal',
            activity: 42,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 89012,
          },
          {
            id: '1036',
            name: 'Clara Fischer',
            country: { name: 'Austria', code: 'at' },
            company: 'Fischer Innovations',
            date: new Date(2017, 4, 21),
            status: 'unqualified',
            activity: 39,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 12345,
          },
          {
            id: '1037',
            name: 'Amir Hosseini',
            country: { name: 'Iran', code: 'ir' },
            company: 'Hosseini Group',
            date: new Date(2020, 7, 8),
            status: 'new',
            activity: 61,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 45634,
          },
          {
            id: '1038',
            name: 'Luna Gonzalez',
            country: { name: 'Colombia', code: 'co' },
            company: 'Gonzalez Ventures',
            date: new Date(2016, 8, 12),
            status: 'qualified',
            activity: 48,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 67856,
          },
          {
            id: '1039',
            name: 'Khalid Mahmoud',
            country: { name: 'Qatar', code: 'qa' },
            company: 'Mahmoud Enterprises',
            date: new Date(2019, 3, 27),
            status: 'proposal',
            activity: 55,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 34578,
          },
          {
            id: '1040',
            name: 'Freya Olsen',
            country: { name: 'Finland', code: 'fi' },
            company: 'Olsen Technologies',
            date: new Date(2018, 5, 19),
            status: 'unqualified',
            activity: 37,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 78956,
          },
          {
            id: '1041',
            name: 'Diego Vargas',
            country: { name: 'Peru', code: 'pe' },
            company: 'Vargas Solutions',
            date: new Date(2021, 5, 14),
            status: 'new',
            activity: 69,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 23412,
          },
          {
            id: '1042',
            name: 'Nadia Ibrahim',
            country: { name: 'Jordan', code: 'jo' },
            company: 'Ibrahim Group',
            date: new Date(2017, 7, 25),
            status: 'qualified',
            activity: 43,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 56734,
          },
          {
            id: '1043',
            name: 'Hugo Muller',
            country: { name: 'Belgium', code: 'be' },
            company: 'Muller Innovations',
            date: new Date(2016, 3, 10),
            status: 'proposal',
            activity: 58,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 89034,
          },
          {
            id: '1044',
            name: 'Sana Ahmed',
            country: { name: 'Bangladesh', code: 'bd' },
            company: 'Ahmed Enterprises',
            date: new Date(2020, 10, 6),
            status: 'unqualified',
            activity: 35,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 12312,
          },
          {
            id: '1045',
            name: 'Jasper Wong',
            country: { name: 'Malaysia', code: 'my' },
            company: 'Wong Technologies',
            date: new Date(2019, 6, 23),
            status: 'new',
            activity: 66,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 45678,
          },
          {
            id: '1046',
            name: 'Valentina Ortiz',
            country: { name: 'Uruguay', code: 'uy' },
            company: 'Ortiz Ventures',
            date: new Date(2018, 1, 30),
            status: 'qualified',
            activity: 50,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 67890,
          },
          {
            id: '1047',
            name: 'Omar Salem',
            country: { name: 'Kuwait', code: 'kw' },
            company: 'Salem Solutions',
            date: new Date(2017, 11, 17),
            status: 'proposal',
            activity: 72,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 34512,
          },
          {
            id: '1048',
            name: 'Elise Dubois',
            country: { name: 'Luxembourg', code: 'lu' },
            company: 'Dubois Group',
            date: new Date(2021, 6, 28),
            status: 'unqualified',
            activity: 46,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 78934,
          },
          {
            id: '1049',
            name: 'Caleb Park',
            country: { name: 'Hong Kong', code: 'hk' },
            company: 'Park Enterprises',
            date: new Date(2016, 9, 4),
            status: 'new',
            activity: 54,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 23456,
          },
          {
            id: '1050',
            name: 'Aria Torres',
            country: { name: 'Costa Rica', code: 'cr' },
            company: 'Torres Innovations',
            date: new Date(2019, 12, 11),
            status: 'qualified',
            activity: 77,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 56789,
          },
          {
            id: '1051',
            name: 'Ravi Sharma',
            country: { name: 'Sri Lanka', code: 'lk' },
            company: 'Sharma Tech',
            date: new Date(2018, 4, 15),
            status: 'proposal',
            activity: 40,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 89012,
          },
          {
            id: '1052',
            name: 'Leila Moussa',
            country: { name: 'Tunisia', code: 'tn' },
            company: 'Moussa Group',
            date: new Date(2017, 5, 26),
            status: 'unqualified',
            activity: 33,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 12345,
          },
          {
            id: '1053',
            name: 'Finn Murphy',
            country: { name: 'Iceland', code: 'is' },
            company: 'Murphy Solutions',
            date: new Date(2020, 2, 20),
            status: 'new',
            activity: 70,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 45634,
          },
          {
            id: '1054',
            name: 'Camila Diaz',
            country: { name: 'Paraguay', code: 'py' },
            company: 'Diaz Ventures',
            date: new Date(2016, 7, 31),
            status: 'qualified',
            activity: 49,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 67856,
          },
          {
            id: '1055',
            name: 'Yusuf Omar',
            country: { name: 'Oman', code: 'om' },
            company: 'Omar Enterprises',
            date: new Date(2019, 10, 8),
            status: 'proposal',
            activity: 57,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 34578,
          },
          {
            id: '1056',
            name: 'Sofia Kowalski',
            country: { name: 'Poland', code: 'pl' },
            company: 'Kowalski Tech',
            date: new Date(2018, 3, 12),
            status: 'unqualified',
            activity: 38,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 78956,
          },
          {
            id: '1057',
            name: 'Elijah Kim',
            country: { name: 'Philippines', code: 'ph' },
            company: 'Kim Solutions',
            date: new Date(2021, 7, 16),
            status: 'new',
            activity: 63,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 23412,
          },
          {
            id: '1058',
            name: 'Isabelle Lefevre',
            country: { name: 'Monaco', code: 'mc' },
            company: 'Lefevre Group',
            date: new Date(2017, 8, 27),
            status: 'qualified',
            activity: 44,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 56734,
          },
          {
            id: '1059',
            name: 'Malik Zaid',
            country: { name: 'Bahrain', code: 'bh' },
            company: 'Zaid Enterprises',
            date: new Date(2016, 6, 19),
            status: 'proposal',
            activity: 68,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 89034,
          },
          {
            id: '1060',
            name: 'Lila Costa',
            country: { name: 'Ecuador', code: 'ec' },
            company: 'Costa Innovations',
            date: new Date(2020, 4, 25),
            status: 'unqualified',
            activity: 41,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 12312,
          },
          {
            id: '1061',
            name: 'Theo Bakker',
            country: { name: 'Netherlands', code: 'nl' },
            company: 'Bakker Tech',
            date: new Date(2019, 2, 14),
            status: 'new',
            activity: 65,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 45678,
          },
          {
            id: '1062',
            name: 'Amina Bello',
            country: { name: 'Nigeria', code: 'ng' },
            company: 'Bello Solutions',
            date: new Date(2018, 9, 29),
            status: 'qualified',
            activity: 52,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 67890,
          },
          {
            id: '1063',
            name: 'Roman Novak',
            country: { name: 'Czech Republic', code: 'cz' },
            company: 'Novak Enterprises',
            date: new Date(2017, 1, 23),
            status: 'proposal',
            activity: 59,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 34512,
          },
          {
            id: '1064',
            name: 'Zara Khan',
            country: { name: 'Afghanistan', code: 'af' },
            company: 'Khan Group',
            date: new Date(2021, 8, 10),
            status: 'unqualified',
            activity: 47,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 78934,
          },
          {
            id: '1065',
            name: 'Luca Ferreira',
            country: { name: 'Angola', code: 'ao' },
            company: 'Ferreira Ventures',
            date: new Date(2016, 2, 18),
            status: 'new',
            activity: 55,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 23456,
          },
          {
            id: '1066',
            name: 'Hana Suzuki',
            country: { name: 'Taiwan', code: 'tw' },
            company: 'Suzuki Innovations',
            date: new Date(2019, 11, 5),
            status: 'qualified',
            activity: 78,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 56789,
          },
          {
            id: '1067',
            name: 'Omar Vargas',
            country: { name: 'Venezuela', code: 've' },
            company: 'Vargas Solutions',
            date: new Date(2018, 10, 13),
            status: 'proposal',
            activity: 46,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 89012,
          },
          {
            id: '1068',
            name: 'Elisa Marino',
            country: { name: 'Malta', code: 'mt' },
            company: 'Marino Group',
            date: new Date(2017, 6, 8),
            status: 'unqualified',
            activity: 39,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 12345,
          },
          {
            id: '1069',
            name: 'Kai Lehmann',
            country: { name: 'Estonia', code: 'ee' },
            company: 'Lehmann Tech',
            date: new Date(2020, 5, 21),
            status: 'new',
            activity: 64,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 45634,
          },
          {
            id: '1070',
            name: 'Nia Robinson',
            country: { name: 'Jamaica', code: 'jm' },
            company: 'Robinson Ventures',
            date: new Date(2016, 4, 16),
            status: 'qualified',
            activity: 51,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 67856,
          },
          {
            id: '1071',
            name: 'Aditya Rao',
            country: { name: 'Nepal', code: 'np' },
            company: 'Rao Enterprises',
            date: new Date(2019, 7, 30),
            status: 'proposal',
            activity: 62,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 34578,
          },
          {
            id: '1072',
            name: 'Lina Petrović',
            country: { name: 'Serbia', code: 'rs' },
            company: 'Petrović Solutions',
            date: new Date(2018, 2, 25),
            status: 'unqualified',
            activity: 44,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 78956,
          },
          {
            id: '1073',
            name: 'Elias Haddad',
            country: { name: 'Syria', code: 'sy' },
            company: 'Haddad Group',
            date: new Date(2021, 9, 17),
            status: 'new',
            activity: 67,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 23412,
          },
          {
            id: '1074',
            name: 'Mila Santos',
            country: { name: 'Dominican Republic', code: 'do' },
            company: 'Santos Innovations',
            date: new Date(2017, 3, 19),
            status: 'qualified',
            activity: 53,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 56734,
          },
          {
            id: '1075',
            name: 'Samir Khalil',
            country: { name: 'Iraq', code: 'iq' },
            company: 'Khalil Enterprises',
            date: new Date(2016, 8, 22),
            status: 'proposal',
            activity: 70,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 89034,
          },
          {
            id: '1076',
            name: 'Anya Volkov',
            country: { name: 'Ukraine', code: 'ua' },
            company: 'Volkov Tech',
            date: new Date(2020, 3, 14),
            status: 'unqualified',
            activity: 48,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 12312,
          },
          {
            id: '1077',
            name: 'Matej Horvat',
            country: { name: 'Croatia', code: 'hr' },
            company: 'Horvat Solutions',
            date: new Date(2019, 1, 9),
            status: 'new',
            activity: 61,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 45678,
          },
          {
            id: '1078',
            name: 'Sanaa Youssef',
            country: { name: 'Yemen', code: 'ye' },
            company: 'Youssef Ventures',
            date: new Date(2018, 5, 27),
            status: 'qualified',
            activity: 55,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 67890,
          },
          {
            id: '1079',
            name: 'Leon Fischer',
            country: { name: 'Slovakia', code: 'sk' },
            company: 'Fischer Enterprises',
            date: new Date(2017, 12, 4),
            status: 'proposal',
            activity: 66,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 34512,
          },
          {
            id: '1080',
            name: 'Alya Nasser',
            country: { name: 'Albania', code: 'al' },
            company: 'Nasser Group',
            date: new Date(2021, 10, 22),
            status: 'unqualified',
            activity: 49,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 78934,
          },
          {
            id: '1081',
            name: 'Jonas Klein',
            country: { name: 'Latvia', code: 'lv' },
            company: 'Klein Solutions',
            date: new Date(2016, 1, 28),
            status: 'new',
            activity: 58,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 23456,
          },
          {
            id: '1082',
            name: 'Esme Rivera',
            country: { name: 'Puerto Rico', code: 'pr' },
            company: 'Rivera Innovations',
            date: new Date(2019, 4, 13),
            status: 'qualified',
            activity: 79,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 56789,
          },
          {
            id: '1083',
            name: 'Karim Boudiaf',
            country: { name: 'Algeria', code: 'dz' },
            company: 'Boudiaf Enterprises',
            date: new Date(2018, 7, 19),
            status: 'proposal',
            activity: 50,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 89012,
          },
          {
            id: '1084',
            name: 'Lara Mendes',
            country: { name: 'Mozambique', code: 'mz' },
            company: 'Mendes Group',
            date: new Date(2017, 2, 15),
            status: 'unqualified',
            activity: 43,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 12345,
          },
          {
            id: '1085',
            name: 'Tomasz Nowak',
            country: { name: 'Poland', code: 'pl' },
            company: 'Nowak Tech',
            date: new Date(2020, 6, 30),
            status: 'new',
            activity: 68,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 45634,
          },
          {
            id: '1086',
            name: 'Ines Carvalho',
            country: { name: 'Angola', code: 'ao' },
            company: 'Carvalho Ventures',
            date: new Date(2016, 9, 25),
            status: 'qualified',
            activity: 54,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 67856,
          },
          {
            id: '1087',
            name: 'Yasin Farooq',
            country: { name: 'Pakistan', code: 'pk' },
            company: 'Farooq Solutions',
            date: new Date(2019, 8, 16),
            status: 'proposal',
            activity: 67,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 34578,
          },
          {
            id: '1088',
            name: 'Evelyn Soto',
            country: { name: 'Guatemala', code: 'gt' },
            company: 'Soto Enterprises',
            date: new Date(2018, 11, 21),
            status: 'unqualified',
            activity: 46,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 78956,
          },
          {
            id: '1089',
            name: 'Arlo Hansen',
            country: { name: 'Greenland', code: 'gl' },
            company: 'Hansen Tech',
            date: new Date(2021, 11, 8),
            status: 'new',
            activity: 62,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 23412,
          },
          {
            id: '1090',
            name: 'Safia Amari',
            country: { name: 'Algeria', code: 'dz' },
            company: 'Amari Group',
            date: new Date(2017, 4, 29),
            status: 'qualified',
            activity: 57,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 56734,
          },
          {
            id: '1091',
            name: 'Mateo Alvarez',
            country: { name: 'Bolivia', code: 'bo' },
            company: 'Alvarez Solutions',
            date: new Date(2016, 10, 14),
            status: 'proposal',
            activity: 71,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 89034,
          },
          {
            id: '1092',
            name: 'Amal Qureshi',
            country: { name: 'Pakistan', code: 'pk' },
            company: 'Qureshi Enterprises',
            date: new Date(2020, 8, 27),
            status: 'unqualified',
            activity: 49,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 12312,
          },
          {
            id: '1093',
            name: 'Luka Jovanović',
            country: { name: 'Serbia', code: 'rs' },
            company: 'Jovanović Tech',
            date: new Date(2019, 5, 12),
            status: 'new',
            activity: 66,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 45678,
          },
          {
            id: '1094',
            name: 'Nour El Din',
            country: { name: 'Egypt', code: 'eg' },
            company: 'El Din Ventures',
            date: new Date(2018, 6, 18),
            status: 'qualified',
            activity: 53,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 67890,
          },
          {
            id: '1095',
            name: 'Emre Yılmaz',
            country: { name: 'Turkey', code: 'tr' },
            company: 'Yılmaz Solutions',
            date: new Date(2017, 9, 23),
            status: 'proposal',
            activity: 68,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 34512,
          },
          {
            id: '1096',
            name: 'Clara Lima',
            country: { name: 'Brazil', code: 'br' },
            company: 'Lima Group',
            date: new Date(2021, 12, 15),
            status: 'unqualified',
            activity: 47,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 78934,
          },
          {
            id: '1097',
            name: 'Jian Zhang',
            country: { name: 'China', code: 'cn' },
            company: 'Zhang Tech',
            date: new Date(2016, 5, 20),
            status: 'new',
            activity: 59,
            representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
            balance: 23456,
          },
          {
            id: '1098',
            name: 'Anika Gupta',
            country: { name: 'India', code: 'in' },
            company: 'Gupta Enterprises',
            date: new Date(2019, 3, 17),
            status: 'qualified',
            activity: 80,
            representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
            balance: 56789,
          },
          {
            id: '1099',
            name: 'Tara O’Brien',
            country: { name: 'Ireland', code: 'ie' },
            company: 'O’Brien Solutions',
            date: new Date(2018, 8, 24),
            status: 'proposal',
            activity: 52,
            representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
            balance: 89012,
          },
          {
            id: '1100',
            name: 'Viktor Ivanov',
            country: { name: 'Bulgaria', code: 'bg' },
            company: 'Ivanov Group',
            date: new Date(2017, 7, 11),
            status: 'unqualified',
            activity: 45,
            representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
            balance: 12345,
          },
    ]);
  }
}